### ISSUE TITLE
[BBU] Business Model #1: Sustainable Business and Revenue Model 

### ISSUE THREAD

**Issue by aratibaliga** [bedrock-consortium/bbu-gf#2]
## Problem/Concern
What is a financially sustainable business model for a Steward ? Are we convinced that the current incentivization structure guarantees continued long-term participation from Stewards ?

**Comment by vinomaster** [comment]
The proposed business model is [here](https://bedrock-consortium.github.io/bbu-gf/gf_info/business_model_concepts/). Details on specific fees can be viewed in the Partnership Agreement and eventually in [GF-Pricing](https://bedrock-consortium.github.io/bbu-gf/gf_info/fee_schedule/).

**Comment by vinomaster** [comment]
Currently waiting on RFP data but the business model has bene adjusted to be less for Governing Members.
