### ISSUE TITLE
[BBU] Pendulum

### ISSUE THREAD

**Issue by danielbachgit** [bedrock-consortium/bbu-gf#26]
## Problem/Concern
The pendulum diagram speaks to Proprietary, Permissioned versus Public, Permission-less and creating a "balance between open privacy by design and financial risks" which I feel is not the key point.

* [link to problem content](https://bedrock-consortium.github.io/bbu-gf/gf_info/transition/)

## Proposed Solution
I agree that Federated models are not true to the core philosophy of the individual being in possession and control of their verifiable identity attributes to enable peer-to-peer interactions without inter-mediation so I propose that the diagram reflect this and illustrate peer-to-peer and peer-[proprietary]intermediary-peer  

<img width="985" alt="pendulum" src="https://user-images.githubusercontent.com/38143286/80506183-3d26f980-8943-11ea-984d-5fcd31d31034.png">

**Comment by vinomaster** [comment]
This section is not about Federated Models. It is about a transition in the Decentralized Identity community that needed to be balanced. As Bedrock we do not want public writes but we also do not want centralized governance. We seek a balance.

**Comment by vinomaster** [comment]
Triaged via 5/21 GFWG Weekly Scrum Mtg; We are fine with current diagram.
