### ISSUE TITLE
[BBU] Business Model #2: Minimum Quorum and Influence on Membership costs

### ISSUE THREAD

**Issue by aratibaliga** [bedrock-consortium/bbu-gf#3]
## Problem/Concern

To cover just the minimum operational expense as finalized by the consortium, we need a minimum quorum of Stewards willing to pay the set membership costs.
How are Steward membership costs affected if the minimum quorum is not met ?

**Comment by vinomaster** [comment]
In general this analysis needs to be an ongoing task of the [Finance Committee](https://bedrock-consortium.github.io/bbu-gf/gf_controlled/governing_bodies/#finance-committee).

Initially, given budgetary assumptions, the minimum requirements of Stewards is outlined [here](https://bedrock-consortium.github.io/bbu-gf/gf_info/membership/#membership-requirements).

@aratibaliga if this is adequate pls close issue.

**Comment by vinomaster** [comment]
Triaged on 5/21 via GFWG Weekly Scrum.
