### ISSUE TITLE
[BBU] Hostname migration to LF

### ISSUE THREAD

**Issue by vinomaster** [bedrock-consortium/bbu-gf#31]
## Problem/Concern

Work with @tbenzies to migrate [bedrockconsortium.org](bedrockconsortium.org) to LF.

**Comment by tbenzies** [comment]
The process is straightforward and all the info can be found at https://jira.linuxfoundation.org/servicedesk/customer/kb/view/28485232 (including how to initiate the process).

**Comment by vinomaster** [comment]
Handled by LF pre-Soft-launch.
