### ISSUE TITLE
[BBU-RFP] Transaction Endorser dev and Indy build maintence

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#35]
## RFP Topic Area
"Aid members in the development, installation, deployment and configuration, of transaction
endorser code."
## Question
What do you mean by "Transaction Endorser code" here?  Since you are using Hyperledger Indy and Endorser code and logic is already built in to that code base, are you really just talking about configuration?

##RFP Topic Area

Build and Test Services | Develop and maintain build and test tools for use on all environments.
-- | --

##Question
Does this mean that the applicant will be expected to produce their own builds of the Hyperledger Indy Node code, or is this just referring to building and testing the maintenance tools referred to elsewhere in the RFP?

**Comment by vinomaster** [comment]
Transaction Endorser's must adhere to the governance framework. The Indy codebase is baseline. Our onboard process with the Linux Foundation will incorporate write to the ledger such that endorser code can validate TAA signing. It also (unlike base indy) must check for entitlements owned by Endorser.

**Comment by vinomaster** [comment]
Applicant will build and maintain Bedrock Indy Code Base ...

**Comment by francesdr** [comment]
Thanks!

**Comment by francesdr** [comment]
We have more questions:
[Questions for the Bedrock RFP.docx](https://github.com/bedrock-consortium/bbu-gf/files/4601257/Questions.for.the.Bedrock.RFP.docx)

**Comment by vinomaster** [comment]
I realized you are new to github so trying to help here ....Not sure what company you represent but it would be helpful to create a question for each in your word doc. Pls make sure that each is a specific question.  For example, the status of the BBU within LF is outside of the scope of this RFP. Respondents need to assume BBU is a legal entity that can pay for services. Please use the [RFP Template](https://github.com/bedrock-consortium/bbu-gf/issues/new/choose) for each.

**Comment by francesdr** [comment]
thanks for the help - will do. Can I still submit questions today?

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
