### ISSUE TITLE
[BBU-RFP] Indicio.Tech RFP Questions

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#36]
## RFP Topic Area

New Steward onboarding | Manage ledger configuration   process for new Steward nodes. | Mandatory

## Question
Would Indicio.tech (if we won the RFP) be in charge of vetting Steward candidates or would the Consortium be inviting and appointing?

**Comment by vinomaster** [comment]
No. Membership in the BBU and obligations of a Steward are outside the scope of the Utility Service Provider's responsibilities.

**Comment by vinomaster** [comment]
The Bedrock Consortium Governance Framework Working Group has approved a 1 week extensions for RFP response submissions. New date is Fri 22-May-2020. The RFP will be updated to reflect this.

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
