### ISSUE TITLE
[BBU-RFP] Indicio.tech Linux Foundation questions

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#37]
## RFP Topic Area
a.	"The Consortium operates a non-profit legal entity, the Bedrock Business Utility (“BBU”), that is an instance of a Linux Foundation Directed Fund Project."
b.	"Respondents should be aware that the process for establishing the BBU Series 1 LLC under the Linux Foundation is still fuzzy so actual process steps and deadlines may change." 

## Question
3.	Clarification on these points: Can we be provided an updated status on progress and whether it has official designation as a Linux Foundation Directed Fund?

**Comment by vinomaster** [comment]
The establishment of the BBU as a LF Project will occur once the Governance Framework WG gets approval from the prospective members to proceed. As with any LF project there is a Launch plan that is undertaken with the LF. This is planned for early June.

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
