### ISSUE TITLE
[BBU-RFP] Indicio.tech - balance between collaboration and competitive value add

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#38]
## RFP Topic Area
"a balance between open collaboration and competitive value-add." 

## Question
What is Bedrock's long-term vision of that balance?

**Comment by vinomaster** [comment]
We will remain focused as a permissioned ledger void of any token and support for public writes.

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
