### ISSUE TITLE
[BBU-RFP] Indicio.tech: collaboration with Bedrock project

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#39]
## RFP Topic Area
"The ideal respondent will demonstrate flexibility, creativity and an openness to community collaboration both within the Bedrock Project and with the ToIP Foundation.”

## Question
How can this be demonstrated in an RFP? Just signify that we will be collaborative?

**Comment by vinomaster** [comment]
With acknowledgement that there will be unknowns as this is a first of a kind public utility. A successful respondent will acknowledge that lessons learned using Bedrock as an exemplar will be used to obtain additional utility contracts. Therefore, collaboration and a willingness to work with the tegh SC and TSC will be required.

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
