### ISSUE TITLE
[BBU] Business Model #3: Operational Budget Details

### ISSUE THREAD

**Issue by aratibaliga** [bedrock-consortium/bbu-gf#4]
## Problem/Concern

Need a detailed breakup of the operational budget and expenditure.

**Comment by vinomaster** [comment]
Budgetary Management is an ongoing task of the [Finance Committee](https://bedrock-consortium.github.io/bbu-gf/gf_controlled/governing_bodies/#finance-committee).

Initially, given budgetary assumptions, the minimum requirements of Stewards is outlined [here](https://bedrock-consortium.github.io/bbu-gf/gf_info/membership/#membership-requirements). We also have an RFP out to invited Utility Service Providers where responses will help shape our budget.

@aratibaliga if this is adequate pls close issue.

**Comment by vinomaster** [comment]
Triaged on 5/21 via GFWG Weekly Scrum.
