### ISSUE TITLE
[BBU-RFP] Indicio.tech: Financial support

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#40]
## RFP Topic Area
Consortium membership

## Question

We like more information on the financial contractual obligations members of this consortium will have.

**Comment by vinomaster** [comment]
You are applying to be a Utility Service Provider to a public non-profit legal entity. You are being asked to respond to bid for services which you have expertise in providing. 

Would you request financial obligations of investors in a business you are considering as a client? This question is not relevant to demonstrate your ability to provide the required services.

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
