### ISSUE TITLE
[BBU-RFP] Indicio.tech: ToIP group

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#41]
## RFP Topic Area
ToIP Foundation 

## Question
8.	We were not included in the Founding group of ToIP. Will applications only be considered from those already in the group. We are in the process of applying.

**Comment by vinomaster** [comment]
Neither participation in ToIP nor Bedrock is required by qualified Utility Service Providers.

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
