### ISSUE TITLE
[BBU-RFP] Indicio.tech: Automatic Software Upgrades

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#42]
## RFP Topic Area

Automatic Software Upgrades | Process automation tool   development. | Mandatory
-- | -- | --

## Question
Does this include automatic security upgrades as well

**Comment by vinomaster** [comment]
The Utility Service Provider contracted by the Bedrock Consortium will be responsible for monitoring the health of the utility (network). This includes working with the technical project (TSC) to establish and maintain a version of Indy referred to as the Bedrock Open Source Code.

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
