### ISSUE TITLE
[BBU-RFP] Final question! Indicio.tech Method name reg services

### ISSUE THREAD

**Issue by francesdr** [bedrock-consortium/bbu-gf#44]
## RFP Topic Area

Method Name   Registration Services | Registration   with known/trusted UR  servers. | Mandatory
-- | -- | --

## Question
10.	Please clarify this segment and why it is needed

**Comment by vinomaster** [comment]
E will have a dedicated did method we may have to install it on specific universal resolver servers. Again this goes to the topic of flexibility and collaboration as we do not know what we don’t know

**Comment by vinomaster** [comment]
RFP Process has entered review stage.
