### ISSUE TITLE
[BBU] Extension Request

### ISSUE THREAD

**Issue by haggs793** [bedrock-consortium/bbu-gf#45]
Our team would like to request an extension to this RFP for more time to formulate our response.

**Comment by vinomaster** [comment]
We will raise this request in our Working Group session Thursday.

**Comment by vinomaster** [comment]
The Bedrock Consortium Governance Framework Working Group has approved a 1 week extensions for RFP response submissions. New date is Fri 22-May-2020. The RFP will be updated to reflect this.
