### ISSUE TITLE
[BBU] Member briefing deck

### ISSUE THREAD

**Issue by bharatUSAA** [bedrock-consortium/bbu-gf#47]
## Problem/Concern
In the slide arrangements, should we talk about ToIP and BBU first and then talk later about what happens on the ledger (DID explanation)?
* [link to problem content]()

## Proposed Solution
If that is agreeable then move slides 3 through 8 to later in the deck

**Comment by vinomaster** [comment]
Given an agenda flow of

**Comment by bharatUSAA** [comment]
Didn't mean ToIP is a priority. I was implying if it flows better to put the technical workings of DID on the ledger (slides 3-8) to be presented AFTER presenting BBU details. Leaving the agenda as-is works too.
