### ISSUE TITLE
[BBU] Briefing Deck: Simplification of ledger interactions

### ISSUE THREAD

**Issue by bharatUSAA** [bedrock-consortium/bbu-gf#48]
## For slides 4-8, not all the audience may be in the know on the ledger terminology. We may want to add some examples for simplicity in understanding

* [link to problem content]()

## Proposed Solution
a) Clarify public DIDs written to ledger as opposed to private DIDs maintained off-ledger
b) a brief definition of schema - a set of attribute data types and formats that can be part of a credential claim. Eg., the fields within a passport/license document
c) a brief definition of credential - an issuer-specific data fields that can come from one/more schemas and defines the proofs sent by the holder. Eg., proof of education, age, nationality, etc.
d) a brief definition of revocation list - a registry that helps identify the revocation of a private DID of a holder
e) It will also be interesting to elaborate that DIDs create the cryptographic trust between two entities whereas the verifiable credential exchange creates the human trust across the same.
f) also need to move slide 6 to after slide 8 as it is focused on the business model and not ledger interaction

**Comment by vinomaster** [comment]
@bharatUSAA to setup pairing session
