### ISSUE TITLE
[BBU-RFP] Environments

### ISSUE THREAD

**Issue by danielbachgit** [bedrock-consortium/bbu-gf#56]
## RFP Topic Area
Environments

## Question
The Evernym RFP response does not specify the support of DEV, TEST, and PROD environments.  There is one related [incomplete] reference:

"Includes hosting of the chat server, servers necessary for automating business processes, monitoring systems, and small-scale test environments,"

**Comment by vinomaster** [comment]
Moved top trello review card.
