### ISSUE TITLE
[BBU] Business Model #5: Prime Drivers of Revenue

### ISSUE THREAD

**Issue by aratibaliga** [bedrock-consortium/bbu-gf#6]
## Problem/Concern

What is the projected revenue (upper & lower limit) of the consortium for say next 2 years? What are the prime drivers of this revenue? How do Founding Stewards/Stewards participate in revenue generating (sales & business development) activities?

**Comment by vinomaster** [comment]
In general this analysis needs to be an ongoing task of the [Finance Committee](https://bedrock-consortium.github.io/bbu-gf/gf_controlled/governing_bodies/#finance-committee).

Initially, given budgetary assumptions, the minimum requirements of Stewards is outlined [here](https://bedrock-consortium.github.io/bbu-gf/gf_info/membership/#membership-requirements).

@aratibaliga if this is adequate pls close issue.

**Comment by vinomaster** [comment]
Prime drivers are membership fees. Triaged on 5/21 via GFWG Weekly Scrum.
