### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by danielbachgit** [bedrock-consortium/bbu-gf#64]
I think the FAQs are great - my suggestions are minor tweaks:

(1) https://bedrock-consortium.github.io/bbu-gf/faq/#who-owns-the-bedrock-business-utility-bbu

"The members of the Bedrock Consortium represent a collection of international private sector companies and other organizations that **utilize**, operate and manage the Utility."

(2) https://bedrock-consortium.github.io/bbu-gf/faq/#how-does-a-business-benefit-from-joining-the-bbu

"The BBU is an established digital trust ecosystem supplying a **public-**permissioned infrastructure **(open read access but only authorized users will have write access)** to foster accelerated ecosystem adoption eliminating the need for individual organizations to “grow their own” – reducing cost and complexity and improving speed to market when implementing a solution."

(3) https://bedrock-consortium.github.io/bbu-gf/faq/#who-is-responsible-for-hosting-and-managing-a-node
"Any member of the Bedrock Business Utility that is required to host a utility infrastructure node is considered a Steward and is responsible for the financial demands of hosting a node. Such expenditures are considered out-of-pocket expenses and are not related to the members annual membership obligations. See membership types."  There is no mention of Node Hosting SLAs; perhaps this is not an FAQ item but it does not appear in the reference either.

**Comment by bharatUSAA** [comment]
@vinomaster This can be closed. Part of the same pull request.
