### ISSUE TITLE
[BBU] Business Model #6: Rate slabs for subscribers

### ISSUE THREAD

**Issue by aratibaliga** [bedrock-consortium/bbu-gf#7]
## Problem/Concern

Identify and state rate slabs for subscribers.

**Comment by vinomaster** [comment]
In general this analysis needs to be an ongoing task of the [Finance Committee](https://bedrock-consortium.github.io/bbu-gf/gf_controlled/governing_bodies/#finance-committee).

Initially, we are assuming $40K buys packages of 50 trx with the option to procure additional packages of 50 trxs for at $10K per occurrence. This will eventually be outlined [here](https://bedrock-consortium.github.io/bbu-gf/gf_info/fee_schedule/#subscription-packages).
 
@aratibaliga if this is adequate pls close issue.

**Comment by vinomaster** [comment]
Triaged on 5/21 via GFWG Weekly Scrum.
