### ISSUE TITLE
[BBU] Broken or incomplete links

### ISSUE THREAD

**Issue by vinomaster** [bedrock-consortium/bbu-gf#75]
## Problem/Concern

Accenture has reported the following broken links:

- Participation Agreement under Governing Board: https://bedrock-consortium.github.io/bbu-gf/gf_controlled/governing_bodies/ 
- Bylaws: https://bedrock-consortium.github.io/bbu-gf/gf_controlled/by_laws/
- ToIP Glossary link inactive: https://bedrock-consortium.github.io/bbu-gf/gf_info/glossary/ 
- NIST Glossary: A Taxonomic Approach to Understanding Emerging Blockchain Identity Management Systems (p50-51) says that it is a whitepaper that has been withdrawn. Should it still be a reference document?
Member Business Policies goes to Steward Business Policies: https://bedrock-consortium.github.io/bbu-gf/gf_legal/legal_arch/

**Comment by bharatUSAA** [comment]
Assigning it to me (bharat).

**Comment by bharatUSAA** [comment]
@vinomaster This can be closed. I don't have privilege to close the issue. The last items on member and steward confusion was fixed a while back and seems to have resurfaced? I will open a new issue for that.
