### ISSUE TITLE
[BBU] Business Model #7: Success of BBU 

### ISSUE THREAD

**Issue by aratibaliga** [bedrock-consortium/bbu-gf#8]
## Problem/Concern

What can we do as Founding Stewards to work towards the success of BBU ?
-Marketing
-Target specific industries ?

**Comment by vinomaster** [comment]
Initially the goal here is for all prospective members to help socialize the BBU and get interested members onboarded. Once we get started as a project each member will need to contribute time/resources to the [various working groups ](https://bedrock-consortium.github.io/bbu-gf/gf_controlled/governing_bodies/).

**Comment by vinomaster** [comment]
@aratibaliga if adequate pls close.

**Comment by vinomaster** [comment]
Need to check that briefing deck has a slide mentioning all the initial WGs. If missing we need slide.

**Comment by vinomaster** [comment]
Exhibit B of Participation Agreement (the Charter) outlines obligations for Stewards whereby our membership MUST provide resources to the BBU Project and WGs. Net - each member will need to contribute time/resources to the various working groups .
